### ISSUE TITLE
Uvoz tabel

### ISSUE THREAD

**Issue by LacenS** [jaanos/APPR-2014-15#7]
pri uvozu 3. tabele se mi tabela izrise, ne morem pa spremenit imen stolpcev ali vrstic. Izpise mi:
Error in `colnames<-`(`*tmp*`, value = "er") : 
  attempt to set 'colnames' on an object with less than two dimensions

(program je v mapi uvoz, funkcija: uvoz_tabele3)

Hvala za pomoc!
lp,
Spela

**Comment by LacenS** [comment]
sem ze resila z data. frame :)
Hvala

**Comment by jaanos** [comment]
Če hočeš odpreti issue glede svojega projekta, ga odpri na svojem repozitoriju (kot si prvotno storila) - bom obveščen glede tega, ker sem izbral, da opazujem ("watch") vse vaše repozitorije. Tukaj lahko odpreš issue, če je kaj narobe z mojim programom.

**Comment by LacenS** [comment]
Velja :) hvala
